In [92]:

import numpy as np

In [93]:
scalar_value = 10
simple_vector = np.array([1, 5, 2, 3])
simple_matrix = np.array([[4, 3, 2, 1], [7, 5, 8, 2]])

In [94]:
simple_vector

array([1, 5, 2, 3])

In [95]:
wrong_vector = np.append(simple_vector, 15)
wrong_vector

array([ 1,  5,  2,  3, 15])

In [96]:
simple_matrix

array([[4, 3, 2, 1],
       [7, 5, 8, 2]])

In [97]:
def matsum_vector_vector(vector_first, vector_second):
    assert len(vector_first.shape) == len(vector_second.shape) == 1, 'Vectors calculated should be one-columns arrays'
    assert len(vector_first) == len(vector_second), 'Vectors calculated should be of equal length.'
    return [v_f + v_s for v_f, v_s in zip(vector_first, vector_second)]
matsum_vector_vector(simple_vector, simple_vector)

[2, 10, 4, 6]

In [98]:
simple_vector + simple_vector

array([ 2, 10,  4,  6])

In [99]:
matsum_vector_vector(simple_vector, simple_matrix)

AssertionError: Vectors calculated should be one-columns arrays

In [100]:
matsum_vector_vector(simple_vector, wrong_vector)

AssertionError: Vectors calculated should be of equal length.

In [101]:
def matsum_vector_matrix(vector, matrix):
    assert len(vector) == matrix.shape[1], 'Vector length should be equal to columns number of the matrix.'
    result = []
    for row in matrix:
        rows = []
        for index, row_value in enumerate(row):
            current_value = row_value + vector[index]
            rows.append(current_value)
        result.append(rows)
    print(result)

In [102]:
matsum_vector_matrix(simple_vector, simple_matrix)

[[5, 8, 4, 4], [8, 10, 10, 5]]


In [103]:
simple_vector + simple_matrix

array([[ 5,  8,  4,  4],
       [ 8, 10, 10,  5]])

In [104]:
matsum_vector_matrix(wrong_vector, simple_matrix)

AssertionError: Vector length should be equal to columns number of the matrix.

In [105]:
def matsum_matrix_matrix(matrix_first, matrix_second):
    assert matrix_first.shape == matrix_second.shape, 'Matrixes should be of the same size.'
    return [[v_f + v_s for v_f, v_s in zip(row_f, row_s)] for row_f, row_s in zip(matrix_first, matrix_second)]
matsum_matrix_matrix(simple_matrix,simple_matrix)

[[8, 6, 4, 2], [14, 10, 16, 4]]

In [106]:
simple_matrix + simple_matrix

array([[ 8,  6,  4,  2],
       [14, 10, 16,  4]])

In [107]:
wrong_matrix = np.vstack([simple_matrix, [10, 11, 12, 13]])
wrong_matrix

array([[ 4,  3,  2,  1],
       [ 7,  5,  8,  2],
       [10, 11, 12, 13]])

In [108]:
matsum_matrix_matrix(simple_matrix, wrong_matrix)

AssertionError: Matrixes should be of the same size.

In [109]:
def matmul_scalar_vector(scalar, vector):
    return [scalar * value for value in vector]
matmul_scalar_vector(scalar_value, simple_vector)

[10, 50, 20, 30]

In [118]:
np.dot(scalar_value, simple_vector)

array([10, 50, 20, 30])

In [111]:
def matmul_scalar_matrix(scalar, matrix):
    return [[scalar * value for value in row_matrix] for row_matrix in matrix]
matmul_scalar_vector(scalar_value, simple_matrix)

[array([40, 30, 20, 10]), array([70, 50, 80, 20])]

In [117]:
np.dot(scalar_value, simple_matrix)

array([[40, 30, 20, 10],
       [70, 50, 80, 20]])

In [113]:
def matmul_matrix_matrix(matrix_first, matrix_second):
    assert matrix_first.shape[1] == matrix_second.shape[0], 'matrix_first columns number should be equal to the matrix_second rows number'
    result = []
    matrix_second_t = matrix_second.T
    for row_f in matrix_first:
        row = []
        for row_s in matrix_second_t:
            tmp = 0
            for index, value_f in enumerate(row_f):
                tmp += value_f * row_s[index]
            row.append(tmp)
        result.append(row)
    print(result)

matmul_matrix_matrix(simple_matrix, simple_matrix.T)

[[30, 61], [61, 142]]


In [116]:
np.dot(simple_matrix, simple_matrix.T)

array([[ 30,  61],
       [ 61, 142]])

In [38]:
matmul_matrix_matrix(simple_matrix,wrong_matrix)

AssertionError: matrix_first columns number should be equal to the matrix_second rows number

In [150]:
def mat_transpose_matrix(matrix):
    result = []
    for column_index in range(matrix.shape[1]):
        row = []
        for row_index in range(matrix.shape[0]):
            row.append(matrix[row_index, column_index])
        result.append(row)
    return np.array(result)


mat_transpose_matrix(simple_matrix)

array([[4, 7],
       [3, 5],
       [2, 8],
       [1, 2]])

In [151]:
simple_matrix.T

array([[4, 7],
       [3, 5],
       [2, 8],
       [1, 2]])